spring.application.name=navaratri_event
spring.datasource.url=jdbc:mysql://localhost:3306/event_management_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

server.port=8080
razorpay.key.id=rzp_test_TT9jHJjUCkdeQJ
razorpay.key.secret=6iLsxfDsuXb8c0hwlY2pI8I6
